### ISSUE TITLE
Pump Code

### ISSUE THREAD

**Issue by kguy18** [kguy18/git_practice#1]
```

esphome:
  name: "garden"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:


# Enable Home Assistant API
api:

ota:

web_server:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Ea7F48"
    password: "8ZqwN8DRJMmF"

captive_portal:

dallas:
  pin: GPIO32
  update_interval: 10s

switch:
  - platform: gpio
    id: lower_shelf_light_relay
    name: "Lower Shelf Light"
    pin: 
      number: 3
      inverted: true
  - platform: gpio
    id: middle_shelf_light_relay
    name: "Middle Shelf Light"
    pin: 
      number: 1
      inverted: true

  - platform: gpio
    id: upper_shelf_light_relay
    name: "Upper Shelf Light"
    pin: 
      number: 22
      inverted: true



  - platform: gpio
    id: lower_shelf_pump_relay
    name: "Lower Shelf Pump"
    pin: 
      number: 18
      inverted: true

  - platform: gpio
    id: middle_shelf_pump_relay
    name: "Middle Shelf Pump"
    pin: 
      number: 19
      inverted: true

  - platform: gpio
    id: upper_shelf_pump_relay
    name: "Upper Shelf Pump"
    pin: 
      number: 21
      inverted: true


  - platform: gpio
    id: lower_shelf_heat_mat_relay
    name: "Lower Shelf Heat Mat"
    pin: 
      number: 16
      inverted: true
  - platform: gpio
    id: middle_shelf_heat_mat_relay
    name: "Middle Shelf Heat Mat"
    pin: 
      number: 17
      inverted: true
  - platform: gpio
    id: uppper_shelf_heat_mat_relay
    name: "Upper Shelf Heat Mat"
    pin: 
      number: 5
      inverted: true


sensor:
  - platform: dallas
    address: 0x4d03009779da6b28
    name: "Bottom Shelf Temperature F"
    id: lower_shelf_temp_f
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
    on_value_range:
      - above: 50
        below: 95
        then:
          - if:
              condition:
                and:
                  - switch.is_on: lower_shelf_light_relay
                  -  text_sensor.state:
                      id: lower_heat_mat_kill_switch
                      state: "OFF"
                  - switch.is_off: lower_shelf_heat_mat_relay
              then:
                - switch.turn_on: lower_shelf_heat_mat_relay
      - above: 95
        below: 96
        then:
          - switch.turn_off: lower_shelf_heat_mat_relay
      - above: 96
        then:
          - switch.turn_off: lower_shelf_heat_mat_relay
  - platform: dallas
    address:  0xcb0303977903f128
    name: "Middle Shelf Temperature F"
    id: middle_shelf_temp_f
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
  - platform: dallas
    address: 0x4e03009779f9dd28
    name: "Upper Shelf Temperature F"
    id: upper_shelf_temp_f
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"





binary_sensor:
  - platform: gpio
    pin:
      number: 14
      mode: 
        input: True
        pullup: True
    id: water_bucket_sensor
    name: "Water Bucket Sensor"

  - platform: gpio
    pin:
      number: 27
      mode: 
        input: True
        pullup: True
    id: lower_shelf_water_sensor
    name: "Lower Shelf Water Sensor"
    on_press:
      then:
       - switch.turn_off: lower_shelf_pump_relay
    on_release:
      then:
       - switch.turn_on: lower_shelf_pump_relay

  - platform: gpio
    pin:
      number: 26
      mode: 
        input: True
        pullup: True
    id: middle_shelf_water_sensor
    name: "Middle Shelf Water Sensor"
    on_press:
      then:
       - switch.turn_off: middle_shelf_pump_relay
    on_release:
      then:
       - switch.turn_on: middle_shelf_pump_relay

  - platform: gpio
    pin:
      number: 25
      mode: 
        input: True
        pullup: True
    id: upper_shelf_water_sensor
    name: "Upper Shelf Water Sensor"
    on_press:
      then:
       - switch.turn_off: upper_shelf_pump_relay
    on_release:
      then:
       - switch.turn_on: upper_shelf_pump_relay

text_sensor:
  - platform: homeassistant
    name: "lower heat mat kill switch"
    entity_id: input_boolean.lower_shelf_heat_mat_issue
    id: lower_heat_mat_kill_switch
    on_value:
      then:
        if:
          condition:
            text_sensor.state:
              id: lower_heat_mat_kill_switch
              state: "on"
          then:
            switch.turn_off: lower_shelf_heat_mat_relay
          else:
            switch.turn_on: lower_shelf_heat_mat_relay



time:
  - platform: sntp
    on_time:
      - seconds: 0
        minutes: 0
        hours: 4
        then:
            - switch.turn_on: lower_shelf_light_relay 
            - switch.turn_on: middle_shelf_light_relay 
            - switch.turn_on: upper_shelf_light_relay 
      - seconds: 0
        minutes: 0
        hours: 20
        then:
            - switch.turn_off: lower_shelf_light_relay 
            - switch.turn_off: middle_shelf_light_relay 
            - switch.turn_off: upper_shelf_light_relay 

```
